buildscript {
    ext.kotlin_version = "1.9.10" // Update to a version compatible with Gradle 8.10
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:8.1.1" // Update to a compatible Android Gradle Plugin version
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}